version: "2.0"
services:
    servidor:
          build: .
          image: "jboss:desen"
          container_name: "jbossDesen"
          ports: 
            - "8080:8080"
            - "9990:9990"
        #  tty: true
          stdin_open: true
    db: 
       image: postgres
       restart: always
       environment:
          POSTGRES_PASSWORD: "example"
          POSTGRES_USER: "postgres"