version: "3.0"
services:
    servidor:
          build: .
          image: "jboss:desen"
          container_name: "jbossDesen"
          ports: 
            - "8080:8080"
            - "9990:9990"
        #  tty: true
          stdin_open: true
        # Adição do Commando para Iniciar o Servidor  
          command: /root/EAP-7.2.0/bin/./standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0
          networks:
            rede: 
              ipv4_address: 172.20.0.6
    pgdb:
        build: ../PostgreSQL
        image: "postgres:desen"
        container_name: "postgres_teste"
        tty: true
        stdin_open: true
        #command: postgres -D /etc/postgresql/data
        ports: 
           - "5432:5432"
        networks: 
             rede:
               ipv4_address: 172.20.0.9     
    front:
         build: ../Front-End
         image: "frontend:desen"
         container_name: "frontend_desen"
         command: "git pull origin master"
         ports: 
            - "4200:4200"
         tty: true
         stdin_open: true  
         networks: 
              rede:
                ipv4_address: 172.20.0.8            
               
networks:
    rede:
      driver: bridge
      ipam:
        config:
           - subnet: 172.20.0.0/24