version: "3.0"
services:
    servidor:
          build: .
          image: "jboss:desen"
          container_name: "jbossDesen"
          ports: 
            - "8080:8080"
            - "9990:9990"
        #  tty: true
          stdin_open: true
        # Adição do Commando para Iniciar o Servidor  
          command: /root/EAP-7.2.0/bin/./standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0
          networks:
            rede: 
              ipv4_address: 172.20.0.6
    db: 
       build:
          context:  ../PostgreSQL     
       image: "postgres:desen"
       stdin_open: true
      # tty: true
      # restart: always
      #command: service postgresql start
       networks:
            rede: 
              ipv4_address: 172.20.0.5                           
networks:
    rede:
      driver: bridge
      ipam:
        config:
           - subnet: 172.20.0.0/24