version: "2.0"
services:
    servidor:
          build: .
          image: "jboss:desen"
          container_name: "jbossDesen"
          ports: 
            - "8080:8080"
            - "9990:9990"
        #  tty: true
          stdin_open: true
        # Adição do Commando para Iniciar o Servidor  
          command: /root/EAP-7.2.0/bin/./standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0
          networks:
            - rede
    db: 
       image: postgres
       restart: always
       environment:
          POSTGRES_PASSWORD: "example"
          POSTGRES_USER: "postgres"
       networks:
            - rede
networks:
    rede:
      driver: bridge
