version: "3.0"
services: 
      nodeservidor:
         build: .
         image: "nodeserver:des"
         container_name: "nodejsServerDes"
         ports: 
          -  "3000:3000"
         # tty: true
         stdin_open: true
         links:
          - mongodb
         networks: 
              rede:
                ipv4_address: 172.20.0.10
      mongodb:
         container_name: "mongodbDes"
         build: ../MongoDB
         image: "mongodb:des"
         command: "mongod --bind_ip 172.20.0.11"
         ports:
            - "27017:27017"
         tty: true
         stdin_open: true    
         networks: 
              rede:
                ipv4_address: 172.20.0.11

networks:
    rede:
      driver: bridge
      ipam:
        config:
           - subnet: 172.20.0.0/24
