version: "2.0"
services: 
      nodeservidor:
          build: .
          container_name: "nodejsServer"
          ports: 
           -  "3000:3000"
         # tty: true
          stdin_open: true
      mongodb:
         container_name: "mongodbDes"
         build: ../MongoDB
         image: "mongodb:des"
         ports:
            - "27017:27017"
         tty: true
         stdin_open: true    