version: "2.1"
services: 
   postdb: 
       build: .
       container_name: "postgresql"
       tty: true
       stdin_open: true
       ports:
           - 5432:5432
       volumes:
           - my_dbdata:/var/lib/postgresql/data
volumes:
   my_dbdata:           
        

      