version: "2.0"
services: 
   postdb: 
       image: postgres:9.6
       container_name: "postgresql"
#       tty: true
       stdin_open: true
       ports:
           - 5432:5432
       volumes:
           - my_dbdata:/var/lib/postgresql/data
       environment: 
         - POSTGRES_DB=pgweb
         - POSTGRES_USER=postgres
         - TZ=GMT    
volumes:
   my_dbdata:           
        

      