version: "2.0"
services: 
   postdb: 
        build:  .
        image: "postgres:desen"
        container_name: "postgres_teste2"
        tty: true
        stdin_open: true
        #command: postgres -D /etc/postgresql/data
        ports: 
           - "5432:5432"
volumes:
   my_dbdata:           
        

      