# Ambiente de Desenvolvimento para o Desafio -  Oministack da RocketSeat
# Desafio Iniciado na data : 04/08/2019
# Tecnologias Utilizadas:
#
#

FROM ubuntu:16.04
MAINTAINER Emaloka(guih.smi2@outlook.com)
WORKDIR /home/server/nodejs
RUN apt-get update
RUN apt-get install npm -y

# Ferramentas para desenvolvimento
RUN apt-get install nano -y && apt-get install curl -y && apt-get install git -y
CMD ["/bin/bash"]