version: "3.0"
services: 
     front:
         build: .
         image: "frontend:desen"
         container_name: "frontend_desen"
         ports: 
            - "4200:4200"
         tty: true
         stdin_open: true 