version: "3.0"
services: 
    # Ambiente de Desenvolvimento do React
    react:
         build: ../Front-End
         image: "react:desenv"
         container_name: "reactDesenv"
         tty: true
         stdin_open: true
         networks: 
            rede:
                ipv4_address: 172.20.0.10
    # Ambiente de Desenvolvimento do NodeJs           
    nodejs:
         build: '..\Nodejs - Servidor\'
         image: "nodejs:desenv"
         container_name: "nodejsDesenv"
         tty: true
         stdin_open: true
         networks: 
            rede:
                ipv4_address: 172.20.0.11
    # Ambiente de Desenvolvimento do MongoDB           
    mongodb:
         build: ../MongoDB
         image: "mongodb:desenv"
         container_name: "mongodbDesenv"
         command: "mongod --bind_ip 172.20.0.12"
         tty: true
         stdin_open: true     
         networks: 
            rede:
                ipv4_address: 172.20.0.12
networks: 
    rede: 
      driver: bridge
      ipam: 
        config: 
           - subnet: 172.20.0.0/24           