version: "3.0"
services:
      webapp:
          build: .
          image: "bootcamp:nodejs"
          tty: true
          stdin_open: true
          ports: 
            - 3333:3333
          networks: 
              - conexao  
      react:
          build: ../React
          image: "bootcamp:react"
          tty: true
          stdin_open: true 
          ports: 
            - "3000:3000"
          networks: 
               - conexao
      mongodb:
          build: ../MongoDB
          image: "mongodb:des"
          command: "mongod"
          ports:
            - "27017:27017"
          tty: true
          stdin_open: true

networks: 
    conexao:
       driver: bridge            