version:  "3.0"
services:
    ragnarok:
        build: 
              context: ../
              dockerfile: ./Ragnarok-Estudos-Servidor/Dockerfile
        container_name: "ragnarokDes"
        image: "ragnarok:server"
        tty: true
        stdin_open: true
        ports: 
            - "80:80"
            - "3306:3306"
            - "6900:6900"
            - "6121:6121"
            - "5121:5121"