FROM ubuntu:16.04
MAINTAINER guih.smi2@outlook.com(Emaloka)
WORKDIR /home/app/udemy
RUN apt-get update
RUN apt-get install nano -y && apt-get install curl -y
RUN apt-get install git -y
EXPOSE 8080
CMD ["/bin/bash"]