version: "2.0"
services: 
      ambiente:
           build: .
           container_name: "udemyambiente"
           ports: 
              - "8080:8080"
           #command: "echo 'Iniciando Ambiente...'"
           #tty: true
           stdin_open: true